spring:
  datasource:
    url: jdbc:h2:mem:tjtechy
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
#define the api endpoint point
api:
  endpoint:
    base-url: /api/v1
server:
  port: 80


