scrape_configs:
  - job_name: "tjtechy-artifacts-online"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s #how often to scrap
    static_configs:
      - targets: ["host.docker.internal:8080"] #this is for demo purpose, during production, change to production host address

        #host.docker.internal(windows)